"""tabla licitaciones corregida a string

Revision ID: 91fcd8e8bc87
Revises: 
Create Date: 2026-01-28 16:25:20.253117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91fcd8e8bc87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licitaciones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('codigo_estado', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitaciones_id'), 'licitaciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licitaciones_id'), table_name='licitaciones')
    op.drop_table('licitaciones')
    # ### end Alembic commands ###
