"""Migracion inicial limpia

Revision ID: a89730e624a7
Revises: 
Create Date: 2026-02-22 17:51:49.230305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89730e624a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_licitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_estados_licitacion_id'), 'estados_licitacion', ['id'], unique=False)
    op.create_table('organismos',
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('puntaje', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index(op.f('ix_organismos_codigo'), 'organismos', ['codigo'], unique=False)
    op.create_table('palabras_claves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('palabra', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('puntaje_titulo', sa.Integer(), nullable=True),
    sa.Column('puntaje_descripcion', sa.Integer(), nullable=True),
    sa.Column('puntaje_productos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_palabras_claves_id'), 'palabras_claves', ['id'], unique=False)
    op.create_table('licitaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_externo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('puntaje', sa.Integer(), nullable=True),
    sa.Column('justificacion_puntaje', sa.Text(), nullable=True),
    sa.Column('etapa', sa.String(), nullable=True),
    sa.Column('detalle_productos', sa.Text(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_adjudicacion', sa.DateTime(), nullable=True),
    sa.Column('codigo_estado', sa.Integer(), nullable=True),
    sa.Column('codigo_organismo', sa.String(), nullable=True),
    sa.Column('tiene_detalle', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_estado'], ['estados_licitacion.codigo'], ),
    sa.ForeignKeyConstraint(['codigo_organismo'], ['organismos.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitaciones_codigo_externo'), 'licitaciones', ['codigo_externo'], unique=True)
    op.create_index(op.f('ix_licitaciones_id'), 'licitaciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licitaciones_id'), table_name='licitaciones')
    op.drop_index(op.f('ix_licitaciones_codigo_externo'), table_name='licitaciones')
    op.drop_table('licitaciones')
    op.drop_index(op.f('ix_palabras_claves_id'), table_name='palabras_claves')
    op.drop_table('palabras_claves')
    op.drop_index(op.f('ix_organismos_codigo'), table_name='organismos')
    op.drop_table('organismos')
    op.drop_index(op.f('ix_estados_licitacion_id'), table_name='estados_licitacion')
    op.drop_table('estados_licitacion')
    # ### end Alembic commands ###
